all_config:
 github_token: xxxxxx
 dingding:
   - enable:1
   - webhook:xxxxxxx
   - secretKey:xxxxxxx
   - app_name:dingding
 server:
   - enable:0
   - sckey:123123
   - app_name:server
 tgbot:
   - enable:0
   - token:123
   - group_id:123
   - app_name:tgbot